# Generated by Django 4.0 on 2022-01-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='aaaaaa', max_length=255, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
