# Generated by Django 4.0 on 2022-02-23 10:53

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_slug'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
