# Generated by Django 4.0 on 2021-12-24 20:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0011_post_users_liked_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='users_disliked',
            field=models.ManyToManyField(related_name='users_disliked', to=settings.AUTH_USER_MODEL),
        ),
    ]
