# Generated by Django 4.0 on 2021-12-24 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_post_users_disliked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='users_disliked',
        ),
    ]
