# Generated by Django 4.0 on 2021-12-25 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_remove_comment_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
