# Generated by Django 4.0 on 2021-12-25 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
    ]
