# Generated by Django 4.0 on 2022-01-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='body',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
    ]
