# Generated by Django 4.0 on 2022-01-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='slug',
            field=models.CharField(max_length=150, null=True, verbose_name='Slug'),
        ),
    ]
