# Generated by Django 4.0 on 2022-05-06 19:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(max_length=60, validators=[django.core.validators.RegexValidator(message='Molimo Vas koristite samo slova.', regex='/^[\\w\\s]+$/')], verbose_name='city'),
        ),
    ]
