# Generated by Django 4.0 on 2022-05-06 19:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(max_length=60, validators=[django.core.validators.RegexValidator(message='Molimo Vas koristite samo slova.', regex='^[\\w]+([-_\\s]{1}[a-z0-9]+)*$')], verbose_name='city'),
        ),
    ]
