# Generated by Django 4.0 on 2021-12-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'invalid': 'Polje nije validno', 'required': 'Popunite ovo polje'}, max_length=70, unique=True, verbose_name='email adresa'),
        ),
    ]
