# Generated by Django 4.0 on 2021-12-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'invalid': 'Entersadasdasdasdasdid value', 'required': 'aaa'}, max_length=70, unique=True, verbose_name='email'),
        ),
    ]
