# Generated by Django 4.0 on 2021-12-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(default='brod', max_length=60, verbose_name='city'),
            preserve_default=False,
        ),
    ]
