# Generated by Django 4.0 on 2022-01-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_customuser_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Korisnik sa ovom email adresom već postoji.'}, max_length=70, unique=True, verbose_name='email'),
        ),
    ]
